version: 0.2

phases:
  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.pytest.org/en/latest/goodpractices.html>
      - python setup.py pytest

artifacts:
  type: zip
  files:
    - 'template.yml'
    - 'scripts/**/*'
    - 'helloworld/**/*.py'
    - 'appspec.yml'
    - 'requirements.txt'
    - 'setup.py'